# Generated by Django 5.0 on 2023-12-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
