# Generated by Django 5.0 on 2023-12-28 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_stripe_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stripe_id",
        ),
    ]
